import Head from "next/head";

export default function Layout({ children, title = "Irchamzah Portfolio" }) {
  return (
    <div>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="font-poppins text-white">
        <div className="bg-gray-950 min-h-screen">{children}</div>
      </main>
    </div>
  );
}
