import Head from "next/head";
import Image from "next/image";
import { useState } from "react";
import {
  BiLogoJavascript,
  BiLogoPostgresql,
  BiLogoTypescript,
} from "react-icons/bi";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { CiLinkedin } from "react-icons/ci";
import { FaGithub, FaLinkedin } from "react-icons/fa";
import { IoSquareSharp } from "react-icons/io5";
import { MdFileDownload, MdOutlineEmail } from "react-icons/md";
import { RiJavascriptFill } from "react-icons/ri";
import {
  SiBootstrap,
  SiCss3,
  SiHtml5,
  SiJavascript,
  SiKotlin,
  SiLaravel,
  SiMysql,
  SiNextdotjs,
  SiPhp,
  SiPostgresql,
  SiPrisma,
  SiReact,
  SiTailwindcss,
  SiTypescript,
} from "react-icons/si";

export default function Home() {
  const [toggle, setToggle] = useState(1);

  function updateToggle(id) {
    setToggle(id);
  }

  return (
    <div>
      <Head>
        <title>Irchamzah Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="font-poppins text-white">
        <div className="bg-gray-950 min-h-screen">
          {/* Navbar */}
          <nav className="fixed z-50 bg-gray-950 w-full shadow-md shadow-gray-800">
            <div className="flex justify-between py-5 px-5 items-center container mx-auto">
              <h1 className="text-2xl flex">
                <p className="block sm:hidden font-semibold">Irc</p>
                <p className="hidden sm:block font-semibold">Irchamzah</p>
                <IoSquareSharp className="text-sm text-end text-sky-500" />
              </h1>
              <ul className="flex">
                {/* <li className="my-auto mx-3">
                  <BsFillMoonStarsFill className="text-2xl  cursor-pointer" />
                </li> */}
                <li className="">
                  <a
                    href={"/irchamzah_fikri_ababil-resume.pdf"}
                    target="_blank"
                    className=" flex items-center bg-gray-800  py-2 px-3 hover:opacity-80 trasition duration-200  "
                  >
                    <MdFileDownload className="text-2xl mr-2" />
                    Download CV
                  </a>
                </li>
              </ul>
            </div>
          </nav>
          {/* Hero Section */}
          <section className="pt-40 pb-10">
            <div className="container px-5 mx-auto">
              <div className="flex gap-20 items-center">
                <div className="max-w-4xl">
                  <div className="flex">
                    <div className="w-1/2 md:w-full">
                      <h2 className="text-3xl md:text-4xl lg:text-5xl">
                        Irchamzah Fikri Ababil
                      </h2>
                      <h3 className="mt-3 text-sky-500 md:text-xl lg:text-2xl">
                        Web Developer
                      </h3>
                    </div>
                    <div className="object-cover overflow-hidden bg-gray-300 w-32 h-32 relative mx-auto my-auto  justify-end md:hidden">
                      <Image
                        src={"/irchamzah_photo.png"}
                        alt=""
                        width={128}
                        height={128}
                        className=""
                      />
                    </div>
                  </div>
                  <p className="text-xs mt-5 text-justify md:text-sm lg:text-base">
                    A fresh graduate from the State Polytechnic of Jember,
                    majoring in Information Technology, specifically in the
                    Informatics Engineering program (D4). Currently delving into
                    several technologies such as React Js, Next Js, Tailwind
                    CSS, PostgreSQL, Prisma ORM, Mongo DB, Laravel, and Mysql.
                  </p>
                </div>
                <div className=" overflow-hidden min-w-44 max-h-44 bg-gray-300 relative mx-auto my-auto object-center hidden md:block xl:max-h-60">
                  <Image
                    src={"/irchamzah_photo.png"}
                    alt=""
                    width={256}
                    height={256}
                    className="object-cover"
                  />
                </div>
              </div>
            </div>
          </section>
          {/* Web Portfolio Section */}
          <section className="pt-20 pb-10">
            <div className="container px-5 mx-auto">
              <div className="flex items-center gap-4">
                <h2 className="text-2xl font-medium text-sky-500 text-nowrap md:text-3xl">
                  Web Portfolio
                </h2>
                <div className="bg-slate-500 h-[2px] w-full"></div>
              </div>
            </div>
            <div className="container px-5 mx-auto mt-8 md:mt-12">
              <div className="flex gap-6 overflow-x-scroll no-scrollbar md:grid md:grid-cols-3 lg:grid-cols-4">
                {/*  */}
                <div className="overflow-hidden flex flex-col justify-stretch bg-gray-900 min-w-72 md:min-w-full">
                  <a
                    className="relative hover:opacity-70 duration-200"
                    href="http://japernik.vercel.app/
                  "
                    target="_blank"
                  >
                    <div className=" overflow-hidden">
                      <Image
                        src={"/portfolio_website/japernik.png"}
                        alt=""
                        height={350}
                        width={350}
                        className="h-40 object-cover"
                      />
                    </div>
                    <div className="absolute left-0 top-0">
                      <p className="bg-black bg-opacity-50 m-3 px-3 py-1 text-xs rounded">
                        Web
                      </p>
                    </div>
                  </a>
                  <div className="flex flex-col justify-between h-full p-4">
                    <div>
                      <a
                        className="text-base font-bold text-sky-500 xl:text-lg hover:opacity-80 duration-200"
                        href="http://japernik.vercel.app/"
                        target="_blank"
                      >
                        Japernik (Jasa Pernikahan)
                      </a>
                      <div className="text-gray-400 text-xs mt-1">
                        Next JS, TypeScript, Prisma, PostgreSQL, Tailwind CSS
                      </div>
                      <div className="h-[1px] w-24 my-4 bg-gray-400"></div>
                      <p className="text-gray-400 text-xs text-justify xl:text-sm">
                        {/* Sebuah website yang menyediakan berbagai macam kebutuhan
                        persiapan pernikahan. (website ini masih dalam tahap
                        pengembangan)  */}
                        A website that provides a variety of wedding preparation
                        needs. click{" "}
                        <a
                          href="https://github.com/irchamzah/japernik/network"
                          className="underline text-sky-500 hover:opacity-90 text-nowrap"
                        >
                          this link
                        </a>{" "}
                        to see the source code. (This website is still under
                        development)
                      </p>
                    </div>
                    <div>
                      <p className="mt-4 text-xs text-sky-500">
                        Created at 9 June 2024 - Present
                      </p>
                      <p className="mt-1 text-xs text-sky-500">By Irchamzah</p>
                    </div>
                  </div>
                </div>
                {/*  */}
                <div className="overflow-hidden flex flex-col justify-stretch bg-gray-900 min-w-72 md:min-w-full">
                  <a
                    className="relative hover:opacity-70 duration-200"
                    href="https://irchamzah-portfolio.vercel.app/"
                    target="_blank"
                  >
                    <div className="h-50 overflow-hidden">
                      <Image
                        src={"/portfolio_website/irchamzah_portfolio.png"}
                        alt=""
                        height={350}
                        width={350}
                        className="h-40 object-cover"
                      />
                    </div>
                    <div className="absolute left-0 top-0">
                      <p className="bg-black bg-opacity-50 m-3 px-3 py-1 text-xs rounded">
                        Web
                      </p>
                    </div>
                  </a>
                  <div className="flex flex-col justify-between h-full p-4">
                    <div>
                      <a
                        className="text-base font-bold text-sky-500 xl:text-lg hover:opacity-80 duration-200"
                        href="https://irchamzah-portfolio.vercel.app/"
                        target="_blank"
                      >
                        Irchamzah Portfolio
                      </a>
                      <div className="text-gray-400 text-xs mt-1">
                        Next JS, React JS, TypeScript
                      </div>
                      <div className="h-[1px] w-24 my-4 bg-gray-400"></div>
                      <div className="text-gray-400 text-xs text-justify xl:text-sm">
                        {/* Latihan membuat website sosial media seperti thread. */}
                        Practice creating a portfolio website. click{" "}
                        <a
                          href="https://github.com/irchamzah/irchamzah-portfolio/network"
                          className="underline text-sky-500 hover:opacity-90 text-nowrap"
                        >
                          this link
                        </a>{" "}
                        to see the source code.
                      </div>
                    </div>
                    <div>
                      <p className="mt-4 text-xs text-sky-500">
                        Created at 20 April 2024 - 5 May 2024
                      </p>
                      <p className="mt-1 text-xs text-sky-500">By Irchamzah</p>
                    </div>
                  </div>
                </div>
                {/*  */}
                <div className="overflow-hidden flex flex-col justify-stretch bg-gray-900 min-w-72 md:min-w-full">
                  <a
                    className="relative hover:opacity-70 duration-200"
                    href="https://irc-portfolio.vercel.app/"
                    target="_blank"
                  >
                    <div className="h-50 overflow-hidden">
                      <Image
                        src={"/portfolio_website/irc_sosmed.png"}
                        alt=""
                        height={350}
                        width={350}
                        className="h-40 object-cover"
                      />
                    </div>
                    <div className="absolute left-0 top-0">
                      <p className="bg-black bg-opacity-50 m-3 px-3 py-1 text-xs rounded">
                        Web
                      </p>
                    </div>
                  </a>
                  <div className="flex flex-col justify-between h-full p-4">
                    <div>
                      <a
                        className="text-base font-bold text-sky-500 xl:text-lg hover:opacity-80 duration-200"
                        href="https://irc-portfolio.vercel.app/"
                        target="_blank"
                      >
                        Irc Social Media
                      </a>
                      <div className="text-gray-400 text-xs mt-1">
                        Next JS, React JS, TypeScript, MongoDB
                      </div>
                      <div className="h-[1px] w-24 my-4 bg-gray-400"></div>
                      <div className="text-gray-400 text-xs text-justify xl:text-sm">
                        {/* Latihan membuat website sosial media seperti thread. */}
                        Practice creating a social media website like a thread.
                        click{" "}
                        <a
                          href="https://github.com/irchamzah/irc_portfolio/network"
                          className="underline text-sky-500 hover:opacity-90 text-nowrap"
                        >
                          this link
                        </a>{" "}
                        to see the source code.
                      </div>
                    </div>
                    <div>
                      <p className="mt-4 text-xs text-sky-500">
                        Created at 23 March 2024 - 13 April 2024
                      </p>
                      <p className="mt-1 text-xs text-sky-500">By Irchamzah</p>
                    </div>
                  </div>
                </div>
                {/*  */}
                <div className="overflow-hidden flex flex-col justify-stretch bg-gray-900 min-w-72 md:min-w-full">
                  <a
                    className="relative hover:opacity-70 duration-200"
                    href="https://www.youtube.com/watch?v=FkZSDkBGqc4
                  "
                    target="_blank"
                  >
                    <div className=" overflow-hidden">
                      <Image
                        src={"/portfolio_website/IBKWU.png"}
                        alt=""
                        height={350}
                        width={350}
                        className="h-40 object-cover"
                      />
                    </div>
                    <div className="absolute left-0 top-0">
                      <p className="bg-black bg-opacity-50 m-3 px-3 py-1 text-xs rounded">
                        Web
                      </p>
                    </div>
                  </a>
                  <div className="flex flex-col justify-between h-full p-4">
                    <div>
                      <a
                        className="text-base font-bold text-sky-500 xl:text-lg hover:opacity-80 duration-200"
                        href="https://www.youtube.com/watch?v=FkZSDkBGqc4"
                        target="_blank"
                      >
                        IBKWU Polije
                      </a>
                      <div className="text-gray-400 text-xs mt-1">
                        Laravel, MySQL, Tailwind CSS
                      </div>
                      <div className="h-[1px] w-24 my-4 bg-gray-400"></div>
                      <p className="text-gray-400 text-xs text-justify xl:text-sm">
                        {/* Sebuah website company profile milik IBKWU Politeknik
                        Negeri Jember yang menampilkan informasi-informasi
                        terbaru dari IBKWU Polije. */}
                        A company profile website owned by IBKWU State
                        Polytechnic of Jember, displaying the latest information
                        from IBKWU Polije. click{" "}
                        <a
                          href="https://github.com/irchamzah/IBKWU_Laravel/network"
                          className="underline text-sky-500 hover:opacity-90 text-nowrap"
                        >
                          this link
                        </a>{" "}
                        to see the source code.
                      </p>
                    </div>
                    <div>
                      <p className="mt-4 text-xs text-sky-500">
                        Created at 14 March 2023 - 2 June 2023
                      </p>
                      <p className="mt-1 text-xs text-sky-500">By Irchamzah</p>
                    </div>
                  </div>
                </div>
                {/*  */}
                {/*  */}
                <div className="overflow-hidden flex flex-col justify-stretch bg-gray-900 min-w-72 md:min-w-full">
                  <a
                    className="relative hover:opacity-70 duration-200"
                    href="https://github.com/NaufalMahdi/sweetacollection/graphs/contributors"
                    target="_blank"
                  >
                    <div className="h-50 overflow-hidden">
                      <Image
                        src={"/portfolio_website/noimage.jpg"}
                        alt=""
                        height={350}
                        width={350}
                        className="h-40 object-cover"
                      />
                    </div>
                    <div className="absolute left-0 top-0">
                      <p className="bg-black bg-opacity-50 m-3 px-3 py-1 text-xs rounded">
                        Web
                      </p>
                    </div>
                  </a>
                  <div className="flex flex-col justify-between h-full p-4">
                    <div>
                      <a
                        className="text-base font-bold text-sky-500 xl:text-lg hover:opacity-80 duration-200"
                        href="https://github.com/NaufalMahdi/sweetacollection/graphs/contributors"
                        target="_blank"
                      >
                        Sweeta Collection
                      </a>
                      <div className="text-gray-400 text-xs mt-1">
                        React JS, Tailwind CSS, Prisma, MongoDB
                      </div>
                      <div className="h-[1px] w-24 my-4 bg-gray-400"></div>
                      <p className="text-gray-400 text-xs text-justify xl:text-sm">
                        {/* Sweeta Collection merupakan website untuk menyewa baju
                        tari tradisional indonesia. */}{" "}
                        Sweeta Collection is a website for renting traditional
                        Indonesian dance costumes. click{" "}
                        <a
                          href="https://github.com/NaufalMahdi/sweetacollection/graphs/contributors"
                          className="underline text-sky-500 hover:opacity-90 text-nowrap"
                        >
                          this link
                        </a>{" "}
                        to see the source code.
                      </p>
                    </div>
                    <div>
                      <p className="mt-4 text-xs text-sky-500">
                        Created at 1 April 2022 - 26 June 2022
                      </p>
                      <p className="mt-1 text-xs text-sky-500">
                        By Irchamzah & Group 3 Class C
                      </p>
                    </div>
                  </div>
                </div>
                <div className="overflow-hidden flex flex-col justify-stretch bg-gray-900 min-w-72 md:min-w-full">
                  <a
                    className="relative hover:opacity-70 duration-200"
                    href="https://www.youtube.com/watch?v=FPcHrprWOJ8"
                    target="_blank"
                  >
                    <div className="h-50 overflow-hidden">
                      <Image
                        src={"/portfolio_website/KBN.png"}
                        alt=""
                        height={350}
                        width={350}
                        className="h-40 object-cover"
                      />
                    </div>
                    <div className="absolute left-0 top-0">
                      <p className="bg-black bg-opacity-50 m-3 px-3 py-1 text-xs rounded">
                        App
                      </p>
                    </div>
                  </a>
                  <div className="flex flex-col justify-between h-full p-4">
                    <div>
                      <a
                        className="text-base font-bold text-sky-500 xl:text-lg hover:opacity-80 duration-200"
                        href="https://www.youtube.com/watch?v=FPcHrprWOJ8"
                        target="_blank"
                      >
                        KBN App
                      </a>
                      <div className="text-gray-400 text-xs mt-1">MATLAB</div>
                      <div className="h-[1px] w-24 my-4 bg-gray-400"></div>
                      <p className="text-gray-400 text-xs text-justify xl:text-sm">
                        {/* Aplikasi pendeteksi kematangan buah naga berdasarkan
                        warna buah naga. */}
                        An application for detecting dragon fruit ripeness based
                        on dragon fruit color. click{" "}
                        <a
                          href="https://github.com/kurniadhn/Semester_5_Citra_Visual_Buah_Naga/graphs/contributors"
                          className="underline text-sky-500 hover:opacity-90 text-nowrap"
                        >
                          this link
                        </a>{" "}
                        to see the source code.
                      </p>
                    </div>
                    <div>
                      <p className="mt-4 text-xs text-sky-500">
                        Created at 20 December 2021 - 4 January 2022
                      </p>
                      <p className="mt-1 text-xs text-sky-500">
                        By Irchamzah & Group 9 Class C
                      </p>
                    </div>
                  </div>
                </div>
                {/*  */}
                <div className="overflow-hidden flex flex-col justify-stretch bg-gray-900 min-w-72 md:min-w-full">
                  <a
                    className="relative hover:opacity-70 duration-200"
                    href="https://www.youtube.com/watch?v=gyDoLoOcLwk"
                    target="_blank"
                  >
                    <div className="h-50 overflow-hidden">
                      <Image
                        src={"/portfolio_website/sipapah.png"}
                        alt=""
                        height={350}
                        width={350}
                        className="h-40 object-cover"
                      />
                    </div>
                    <div className="absolute left-0 top-0">
                      <p className="bg-black bg-opacity-50 m-3 px-3 py-1 text-xs rounded">
                        Web
                      </p>
                    </div>
                  </a>
                  <div className="flex flex-col justify-between h-full p-4">
                    <div>
                      <a
                        className="text-base font-bold text-sky-500 xl:text-lg hover:opacity-80 duration-200"
                        href="https://www.youtube.com/watch?v=gyDoLoOcLwk"
                        target="_blank"
                      >
                        SIPAPAH - Sistem Informasi Pengolah Sampah
                      </a>
                      <div className="text-gray-400 text-xs mt-1">
                        Laravel, Bootstrap, MySQL
                      </div>
                      <div className="h-[1px] w-24 my-4 bg-gray-400"></div>
                      <p className="text-gray-400 text-xs text-justify xl:text-sm">
                        {/* Aplikasi SIPAPAH merupakan aplikasi pengolah sampah. Tim
                        kami akan menjemput sampah milik penduduk lalu
                        membayarnya berdasarkan berat sampah (plastik, kertas,
                        kardus, dll) */}
                        The SIPAPAH application is a waste management
                        application. Our team will collect waste from residents
                        and pay for it based on the weight of the waste
                        (plastic, paper, cardboard, etc.). click{" "}
                        <a
                          href="https://github.com/irchamzah/Kelompok1_WEB_GolonganB/network"
                          className="underline text-sky-500 hover:opacity-90 text-nowrap"
                        >
                          this link
                        </a>{" "}
                        to see the source code.
                      </p>
                    </div>
                    <div>
                      <p className="mt-4 text-xs text-sky-500">
                        Created at 3 June 2021 - 26 July 2021
                      </p>
                      <p className="mt-1 text-xs text-sky-500">
                        By Irchamzah & Group 1 Class B
                      </p>
                    </div>
                  </div>
                </div>

                {/*  */}
              </div>
            </div>
          </section>
          {/* Programming Skills Section */}
          <section className="pt-20 pb-10">
            <div className="container px-5 mx-auto">
              <div className="flex items-center gap-4">
                <h2 className="text-xl font-medium text-sky-500 text-nowrap md:text-3xl">
                  Programming Skills
                </h2>
                <div className="bg-slate-500 h-[2px] w-full"></div>
              </div>
            </div>
            <div className="container px-5 mx-auto mt-8 md:mt-12">
              <div className="grid grid-cols-4 gap-y-16 gap-x-10 justify-stretch md:gap-x-32">
                {/*  */}
                {/*  */}
                <div className="tailwindcss flex flex-col items-center hover:opacity-60 transition duration-200">
                  <div className="relative p-2 w-full">
                    <div className="">
                      <SiTailwindcss
                        height={128}
                        width={128}
                        className="mx-auto object-center object-contain h-12 w-12 md:h-14 md:w-14 lg:h-20 lg:w-20 xl:h-28 xl:w-28 text-white text-8xl"
                      />
                    </div>
                    <p className="absolute right-0 top-0 bg-indigo-500 rounded-full px-[6px] py-[2px] text-[10px]">
                      Fluent
                    </p>
                  </div>
                  <div className="text-[10px] md:text-sm text-nowrap">
                    Tailwind CSS
                  </div>
                </div>
                {/*  */}
                {/*  */}
                <div className="nexjs flex flex-col items-center hover:opacity-60 transition duration-200">
                  <div className="relative p-2 w-full">
                    <div className="">
                      <SiNextdotjs
                        height={128}
                        width={128}
                        className="mx-auto object-center object-contain h-12 w-12 md:h-14 md:w-14 lg:h-20 lg:w-20 xl:h-28 xl:w-28 text-white text-8xl"
                      />
                    </div>
                    <p className="absolute right-0 top-0 bg-sky-500 rounded-full px-[6px] py-[2px] text-[10px]">
                      Intermediate
                    </p>
                  </div>
                  <div className="text-[10px] md:text-sm">Next JS</div>
                </div>
                {/*  */}
                {/*  */}
                <div className="reactjs flex flex-col items-center hover:opacity-60 transition duration-200">
                  <div className="relative p-2 w-full">
                    <div className="">
                      <SiReact
                        height={128}
                        width={128}
                        className="mx-auto object-center object-contain h-12 w-12 md:h-14 md:w-14 lg:h-20 lg:w-20 xl:h-28 xl:w-28 text-white text-8xl"
                      />
                    </div>
                    <p className="absolute right-0 top-0 bg-sky-500 rounded-full px-[6px] py-[2px] text-[10px]">
                      Intermediate
                    </p>
                  </div>
                  <div className="text-[10px] md:text-sm">React JS</div>
                </div>
                {/*  */}
                {/*  */}
                <div className="javascript flex flex-col items-center hover:opacity-60 transition duration-200">
                  <div className="relative p-2 w-full">
                    <div className="">
                      <SiJavascript
                        height={128}
                        width={128}
                        className="mx-auto object-center object-contain h-12 w-12 md:h-14 md:w-14 lg:h-20 lg:w-20 xl:h-28 xl:w-28 text-white text-8xl"
                      />
                    </div>
                    <p className="absolute right-0 top-0 bg-sky-500 rounded-full px-[6px] py-[2px] text-[10px]">
                      Intermediate
                    </p>
                  </div>
                  <div className="text-[10px] md:text-sm">Javascript</div>
                </div>
                {/*  */}
                {/*  */}
                <div className="typescript flex flex-col items-center hover:opacity-60 transition duration-200">
                  <div className="relative p-2 w-full">
                    <div className="">
                      <SiTypescript
                        height={128}
                        width={128}
                        className="mx-auto object-center object-contain h-12 w-12 md:h-14 md:w-14 lg:h-20 lg:w-20 xl:h-28 xl:w-28 text-white text-8xl"
                      />
                    </div>
                    <p className="absolute right-0 top-0 bg-sky-500 rounded-full px-[6px] py-[2px] text-[10px]">
                      Intermediate
                    </p>
                  </div>
                  <div className="text-[10px] md:text-sm">Typescript</div>
                </div>
                {/*  */}
                {/*  */}
                <div className="prisma flex flex-col items-center hover:opacity-60 transition duration-200">
                  <div className="relative p-2 w-full">
                    <div className="text-center justify-center">
                      <SiPrisma className="mx-auto object-center object-contain h-12 w-12 md:h-14 md:w-14 lg:h-20 lg:w-20 xl:h-28 xl:w-28 text-white text-8xl" />
                    </div>
                    <p className="absolute right-0 top-0 bg-sky-500 rounded-full px-[6px] py-[2px] text-[10px]">
                      Intermediate
                    </p>
                  </div>
                  <div className="text-[10px] md:text-sm">Prisma</div>
                </div>
                {/*  */}
                {/*  */}
                <div className="postgresql flex flex-col items-center hover:opacity-60 transition duration-200">
                  <div className="relative p-2 w-full">
                    <div className="">
                      <BiLogoPostgresql
                        height={128}
                        width={128}
                        className="mx-auto object-center object-contain h-12 w-12 md:h-14 md:w-14 lg:h-20 lg:w-20 xl:h-28 xl:w-28 text-white text-8xl"
                      />
                    </div>
                    <p className="absolute right-0 top-0 bg-sky-500 rounded-full px-[6px] py-[2px] text-[10px]">
                      Intermediate
                    </p>
                  </div>
                  <div className="text-[10px] md:text-sm">PostgreSQL</div>
                </div>

                {/*  */}
                {/*  */}
                <div className="laravel flex flex-col items-center hover:opacity-60 transition duration-200">
                  <div className="relative p-2 w-full">
                    <div className="">
                      <SiLaravel
                        height={128}
                        width={128}
                        className="mx-auto object-center object-contain h-12 w-12 md:h-14 md:w-14 lg:h-20 lg:w-20 xl:h-28 xl:w-28 text-white text-8xl"
                      />
                    </div>
                    <p className="absolute right-0 top-0 bg-sky-500 rounded-full px-[6px] py-[2px] text-[10px]">
                      Intermediate
                    </p>
                  </div>
                  <div className="text-[10px] md:text-sm">Laravel</div>
                </div>
                {/*  */}
                {/*  */}
                <div className="php flex flex-col items-center hover:opacity-60 transition duration-200">
                  <div className="relative p-2 w-full">
                    <div className="">
                      <SiPhp
                        height={128}
                        width={128}
                        className="mx-auto object-center object-contain h-12 w-12 md:h-14 md:w-14 lg:h-20 lg:w-20 xl:h-28 xl:w-28 text-white text-8xl"
                      />
                    </div>
                    <p className="absolute right-0 top-0 bg-sky-500 rounded-full px-[6px] py-[2px] text-[10px]">
                      Intermediate
                    </p>
                  </div>
                  <div className="text-[10px] md:text-sm">PHP</div>
                </div>
                {/*  */}
                {/*  */}
                <div className="mysql flex flex-col items-center hover:opacity-60 transition duration-200">
                  <div className="relative p-2 w-full">
                    <div className="">
                      <SiMysql
                        height={128}
                        width={128}
                        className="mx-auto object-center object-contain h-12 w-12 md:h-14 md:w-14 lg:h-20 lg:w-20 xl:h-28 xl:w-28 text-white text-8xl"
                      />
                    </div>
                    <p className="absolute right-0 top-0 bg-sky-500 rounded-full px-[6px] py-[2px] text-[10px]">
                      Intermediate
                    </p>
                  </div>
                  <div className="text-[10px] md:text-sm">MySQL</div>
                </div>
                {/*  */}
                {/*  */}
                <div className="html5 flex flex-col items-center hover:opacity-60 transition duration-200">
                  <div className="relative p-2 w-full">
                    <div className="">
                      <SiHtml5
                        height={128}
                        width={128}
                        className="mx-auto object-center object-contain h-12 w-12 md:h-14 md:w-14 lg:h-20 lg:w-20 xl:h-28 xl:w-28 text-white text-8xl"
                      />
                    </div>
                    <p className="absolute right-0 top-0 bg-sky-500 rounded-full px-[6px] py-[2px] text-[10px]">
                      Intermediate
                    </p>
                  </div>
                  <div className="text-[10px] md:text-sm">HTML 5</div>
                </div>
                {/*  */}
                {/*  */}
                <div className="css3 flex flex-col items-center hover:opacity-60 transition duration-200">
                  <div className="relative p-2 w-full">
                    <div className="">
                      <SiCss3
                        height={128}
                        width={128}
                        className="mx-auto object-center object-contain h-12 w-12 md:h-14 md:w-14 lg:h-20 lg:w-20 xl:h-28 xl:w-28 text-white text-8xl"
                      />
                    </div>
                    <p className="absolute right-0 top-0 bg-sky-500 rounded-full px-[6px] py-[2px] text-[10px]">
                      Intermediate
                    </p>
                  </div>
                  <div className="text-[10px] md:text-sm">CSS 3</div>
                </div>
                {/*  */}
                {/*  */}
                <div className="kotlin flex flex-col items-center hover:opacity-60 transition duration-200">
                  <div className="relative p-2 w-full">
                    <div className="">
                      <SiKotlin
                        height={128}
                        width={128}
                        className="mx-auto object-center object-contain h-12 w-12 md:h-14 md:w-14 lg:h-20 lg:w-20 xl:h-28 xl:w-28 text-white text-8xl"
                      />
                    </div>
                    <p className="absolute right-0 top-0 bg-gray-500 rounded-full px-[6px] py-[2px] text-[10px]">
                      Basic
                    </p>
                  </div>
                  <div className="text-[10px] md:text-sm">Kotlin</div>
                </div>
                {/*  */}
                {/*  */}
                <div className="bootstrap flex flex-col items-center hover:opacity-60 transition duration-200">
                  <div className="relative p-2 w-full">
                    <div className="">
                      <SiBootstrap
                        height={128}
                        width={128}
                        className="mx-auto object-center object-contain h-12 w-12 md:h-14 md:w-14 lg:h-20 lg:w-20 xl:h-28 xl:w-28 text-white text-8xl"
                      />
                    </div>
                    <p className="absolute right-0 top-0 bg-gray-500 rounded-full px-[6px] py-[2px] text-[10px]">
                      Basic
                    </p>
                  </div>
                  <div className="text-[10px] md:text-sm">Bootstrap</div>
                </div>
                {/*  */}
                {/*  */}
              </div>
            </div>
          </section>
          {/* Work Experience Section */}
          <section className="pt-20 pb-10">
            <div className="container px-5 mx-auto">
              <div className="flex items-center gap-4">
                <h2 className="text-xl font-medium text-sky-500 text-nowrap md:text-3xl">
                  Work Experience
                </h2>
                <div className="bg-slate-500 h-[2px] w-full"></div>
              </div>
            </div>
            <div className="container px-5 mx-auto mt-8 md:mt-12">
              <div className="grid w-full grid-cols-1 gap-10 md:grid-cols-3 ">
                <ul className="flex items-end text-nowrap overflow-x-scroll gap-2 no-scrollbar py-2 h-min md:border-l-2 border-gray-500 md:flex-col md:items-start">
                  <li>
                    <button
                      className={`py-2 px-4 font-semibold ${
                        toggle === 1
                          ? `border-b-2  mb-1 text-gray-200  border-sky-500 md:border-l-2 md:border-b-0 md:ml-2`
                          : `text-gray-500`
                      }`}
                      onClick={() => updateToggle(1)}
                    >
                      Freelance Web Dev
                    </button>
                  </li>
                  <li>
                    <button
                      className={`py-2 px-4 font-semibold ${
                        toggle === 2
                          ? `border-b-2  mb-1 text-gray-200 border-sky-500 md:border-l-2 md:border-b-0 md:ml-2`
                          : `text-gray-500`
                      }`}
                      onClick={() => updateToggle(2)}
                    >
                      PT. Koltiva
                    </button>
                  </li>
                  <li>
                    <button
                      className={`py-2 px-4 font-semibold ${
                        toggle === 3
                          ? `border-b-2  mb-1 text-gray-200 border-sky-500 md:border-l-2 md:border-b-0 md:ml-2`
                          : `text-gray-500`
                      }`}
                      onClick={() => updateToggle(3)}
                    >
                      Freelance Illustrator
                    </button>
                  </li>
                </ul>
                <div className="md:col-span-2">
                  <div className={toggle === 1 ? "col-span-2" : "hidden"}>
                    <p className="text-lg font-semibold text-gray-2 md:text-xl">
                      Web Developer
                    </p>
                    <p className="text-sm md:text-base text-gray-300">
                      Oct 2023 - Present
                    </p>
                    <p className="text-sm md:text-base mt-5 text-gray-300">
                      {/* Saat ini sedang mempelajari React JS, Next JS, MongoDB,
                      Laravel, MySQL, PostgreSQL dan berencana untuk membuka
                      jasa pembuatan website. */}{" "}
                      Currently studying React JS, Next JS, MongoDB, Laravel,
                      MySQL, PostgreSQL and planning to open a website
                      development service.
                    </p>
                    <div className="text-sm md:text-base text-gray-300">
                      <ul className="list-disc list-outside ms-5">
                        <li className="py-1 hidden"></li>
                        <li className="py-1 hidden"></li>
                        <li className="py-1 hidden"></li>
                        <li className="py-1 hidden"></li>
                        <li className="py-1 hidden"></li>
                      </ul>
                    </div>
                  </div>
                  <div className={toggle === 2 ? "col-span-2" : "hidden"}>
                    <p className="text-lg font-semibold text-gray-2 md:text-xl">
                      Product Operation Intern
                    </p>
                    <p className="text-sm md:text-base text-gray-300">
                      8 August 2022 - 31 January 2023
                    </p>
                    <p className="text-sm md:text-base mt-5 text-gray-300">
                      Koltiva is a technology-enabled service company. Koltiva
                      support some of the largest multinational companies by
                      digitizing and verifying global supply chains.
                      Koltiva&apos;s focus is to enhance traceability,
                      inclusiveness, and sustainability.
                    </p>
                    <div className="text-sm md:text-base text-gray-300">
                      <ul className="list-disc list-outside ms-5">
                        <li className="py-1">
                          Helps interact with overseas employees using English.
                        </li>
                        <li className="py-1">
                          Help complete tasks in the Product Operations
                          division.
                        </li>
                        <li className="py-1">
                          Helps provide Directions to Koltiva company
                          application users.
                        </li>
                        <li className="py-1">
                          Replicating a bug that occurred in the Koltiva
                          application used by users.
                        </li>
                        <li className="py-1">
                          Create guidance reports for carrying out work in the
                          Product Operation division.
                        </li>
                      </ul>
                    </div>
                  </div>
                  <div className={toggle === 3 ? "col-span-2" : "hidden"}>
                    <p className="text-lg font-semibold text-gray-2 md:text-xl">
                      Cartoon Illustrator
                    </p>
                    <p className="text-sm md:text-base text-gray-300">
                      12 Jun 2020 - Present
                    </p>
                    <p className="text-sm md:text-base mt-5 text-gray-300">
                      {/* Membuka Jasa pembuatan ilustrasi kartun di website Fiverr
                      dengan total pesanan saat ini mencapai 186 pesanan.
                      Portfolio dapat dilihat pada */}
                      Opening a cartoon illustration service on Fiverr with a
                      total of 186 current orders. The portfolio can be viewed
                      at{" "}
                      <a
                        href="https://www.fiverr.com/ircart_"
                        className="text-sky-500 hover:opacity-70 duration-200 underline"
                      >
                        {/* link ini */}this link.
                      </a>
                    </p>
                    <div className="text-sm md:text-base text-gray-300">
                      <ul className="list-disc list-outside ms-5">
                        <li className="py-1">
                          {/* Total pesanan yang telah selesai mencapai 186 pesanan. */}
                          The total completed orders reached 186 orders.
                        </li>
                        <li className="py-1">
                          {/* Mendapatkan rating sebesar 4.9⭐ dari 5⭐ */}
                          Received a rating of 4.9⭐ out of 5⭐.
                        </li>
                      </ul>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </section>
          {/* Educations Section */}
          <section className="pt-20 pb-10">
            <div className="container px-5 mx-auto">
              <div className="flex items-center gap-4">
                <h2 className="text-2xl font-medium text-sky-500 text-nowrap md:text-3xl">
                  Educations
                </h2>
                <div className="bg-slate-500 h-[2px] w-full"></div>
              </div>
            </div>
            <div className="container px-5 mx-auto mt-8 md:mt-12">
              <div className="flex flex-col gap-10">
                <ul className="flex flex-col overflow-x-scroll gap-4 no-scrollbar">
                  <li className="border-l-2 pl-5 hover:opacity-60 transition duration-200">
                    <a
                      href="https://www.google.com/maps/place/TK+Al+Asy'ari/@-7.8887968,113.8961183,15z/data=!4m2!3m1!1s0x0:0xf2277f12a2baaae9?sa=X&ved=1t:2428&ictx=111"
                      className="md:flex md:justify-between md:items-center"
                    >
                      <div>
                        <div className="font-semibold text-gray-200 md:text-xl">
                          TK Al Asy&apos;ari
                        </div>
                        <div className="text-xs text-gray-400 italic md:text-sm">
                          Wonosari Bondowoso
                        </div>
                      </div>
                      <div className="text-xs text-gray-400 md:text-base">
                        ( 2005 - 2007 )
                      </div>
                    </a>
                  </li>
                  <li className="border-l-2 pl-5 hover:opacity-60 transition duration-200">
                    <a
                      href="https://sddarutthalabah.sch.id/"
                      className="md:flex md:justify-between md:items-center"
                    >
                      <div>
                        <div className="font-semibold text-gray-200 md:text-xl">
                          SD Darut Thalabah
                        </div>
                        <div className="text-xs text-gray-400 italic md:text-sm">
                          Wonosari Bondowoso
                        </div>
                      </div>
                      <div className="text-xs text-gray-400 md:text-base">
                        ( 2007 - 2013 )
                      </div>
                    </a>
                  </li>
                  <li className="border-l-2 pl-5 hover:opacity-60 transition duration-200">
                    <a
                      href="https://www.mtsnj.sch.id/"
                      className="md:flex md:justify-between md:items-center"
                    >
                      <div>
                        <div className="font-semibold text-gray-200 md:text-xl">
                          MTs Nurul Jadid
                        </div>
                        <div className="text-xs text-gray-400 italic md:text-sm">
                          Paiton Probolinggo
                        </div>
                      </div>
                      <div className="text-xs text-gray-400 md:text-base">
                        ( 2013 - 2016 )
                      </div>
                    </a>
                  </li>
                  <li className="border-l-2 pl-5 hover:opacity-60 transition duration-200">
                    <a
                      href="https://www.manuruljadid.sch.id/"
                      className="md:flex md:justify-between md:items-center"
                    >
                      <div>
                        <div className="font-semibold text-gray-200 md:text-xl">
                          MA Nurul Jadid
                        </div>
                        <div className="text-xs text-gray-400 italic md:text-sm">
                          Paiton Probolinggo
                        </div>
                      </div>
                      <div className="text-xs text-gray-400 md:text-base">
                        ( 2016 - 2017 )
                      </div>
                    </a>
                  </li>
                  <li className="border-l-2 pl-5 hover:opacity-60 transition duration-200">
                    <a
                      href="https://www.sman3bondowoso.sch.id/"
                      className="md:flex md:justify-between md:items-center"
                    >
                      <div>
                        <div className="font-semibold text-gray-200 md:text-xl">
                          SMA Negeri 3 Bondowoso
                        </div>
                        <div className="text-xs text-gray-400 italic md:text-sm">
                          Kademangan Bondowoso
                        </div>
                      </div>
                      <div className="text-xs text-gray-400 md:text-base">
                        ( 2017 - 2019 )
                      </div>
                    </a>
                  </li>
                  <li className="border-l-2 pl-5 hover:opacity-60 transition duration-200">
                    <a
                      href="https://jti.polije.ac.id/"
                      className="md:flex md:justify-between md:items-center"
                    >
                      <div>
                        <div className="font-semibold text-gray-200 md:text-xl">
                          D4 (Bachelor Degree) - Informatics Engineering
                        </div>
                        <div className="text-xs text-gray-400 italic md:text-sm">
                          State Polytechnic of Jember GPA (3.82)
                        </div>
                      </div>
                      <div className="text-xs text-gray-400 md:text-base">
                        ( 2019 - 2023 )
                      </div>
                    </a>
                  </li>
                </ul>
              </div>
            </div>
          </section>
          {/* Contacts Section */}
          <section className="pt-20 pb-10">
            <div className="container px-5 mx-auto">
              <div className="flex items-center gap-4">
                <h2 className="text-2xl font-medium text-sky-500 text-nowrap md:text-3xl">
                  Contacts
                </h2>
                <div className="bg-slate-500 h-[2px] w-full"></div>
              </div>
            </div>
            <div className="container px-5 mx-auto mt-8 md:mt-12">
              <div className="flex flex-col gap-10 items-center">
                <p className="text-xl text-sky-500 md:text-2xl">
                  Feel Free to Connect With Me!
                </p>
                <div className="flex flex-col overflow-x-scroll gap-4 no-scrollbar md:flex-row">
                  <a
                    href="mailto:irchamzah.fikri.ababil@gmail.com"
                    className="flex items-center gap-2 hover:opacity-60 transition duration-200"
                  >
                    <div className="text-xl md:text-2xl">
                      <MdOutlineEmail />
                    </div>
                    <div className="text-sm md:text-base">
                      irchamzah.fikri.ababil@gmail.com
                    </div>
                  </a>
                  <a
                    href="www.linkedin.com/in/irchamzah"
                    className="flex items-center gap-2 hover:opacity-60 transition duration-200"
                  >
                    <div className="text-xl md:text-2xl">
                      <FaLinkedin />
                    </div>
                    <div className="text-sm md:text-base">irchamzah</div>
                  </a>
                  <a
                    href="https://github.com/irchamzah"
                    className="flex items-center gap-2 hover:opacity-60 transition duration-200"
                  >
                    <div className="text-xl md:text-2xl">
                      <FaGithub />
                    </div>
                    <div className="text-sm md:text-base">irchamzah</div>
                  </a>
                </div>
              </div>
            </div>
          </section>
        </div>
      </main>
    </div>
  );
}
